#!/bin/bash

yaml=$(helm template postgresql bitnami/postgresql \
	--namespace "$K8SAPP_NAMESPACE" \
	--version "$K8SAPP_UPSTREAM")

## TODO detect Vault if available
## TODO create some secrets in Vault (if Vault)

cat <<<"$yaml" > postgresql.yaml ## TODO remove later
