#!/usr/bin/env bash

: "${K8SAPP_CLUSTER:=dev}"
: "${K8SAPP_NAMESPACE:=redis}"
: "${K8SAPP_UPSTREAM:=20.1.3}"
: "${http_proxy:=}"
: "${https_proxy:=}"
: "${no_proxy:=}"

red=$'\e[31m'
# green=$'\e[32m'
# yellow=$'\e[33m'
# blue=$'\e[34m'
# magenta=$'\e[35m'
# cyan=$'\e[36m'
# white=$'\e[37m'
reset=$'\e[0m'

## sanity check that being run from right directory
if [[ ! -d .git || ! -x build ]];then
	echo "${red}must be run from a K8SAPP repo${reset}"
	exit 1
fi

helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update bitnami

yaml=$(helm template bitnami bitnami/redis \
	--namespace "$K8SAPP_NAMESPACE" \
	--version "$K8SAPP_UPSTREAM")

## TODO detect Vault if available
## TODO create some secrets in Vault (if Vault)

cat <<<"$yaml" > postgresql.yaml ## TODO remove later
